### ISSUE TITLE
Use as left click menu?

### ISSUE THREAD

**Issue by mgk89** [joewalnes/jquery-simple-context-menu#28]
Is it possible to use this menu as a left-click menu instead of right-click?

thanks in advance for your help

**Comment by joewalnes** [comment]
It doesn't support left click, but it's easy to modify the code for your own needs.

Change this line: https://github.com/joewalnes/jquery-simple-context-menu/blob/2f8400075047cf46b21eecbf2708350212ff8dff/jquery.contextmenu.js#L76

From:

``` js
this.on('contextmenu', ...
```

To:

``` js
this.on('click', ...
```
